# -*- coding: utf-8 -*-
"""Exercicios_For_While.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RfPQT7viFwWuFhiDRZ3uujNScC7SMzoo
"""



"""1. Solicitar um numero inteiro positivo N ao usuario.Imprimir os numeros de N a 1. Realizar o exercicio usando loops for e while.

"""

# Entrada de variavel que sera utilizada pelos 2 loops
T = int(input("Entre com numero interio maior que 1 "))
#FOR
print(f"For:", end=" ")
for t in range(T): #Para o contador t dentro do range T faca
  print(f"{T-t}", end="") # comando end para ficar em linha \n, Mostre o calculo de T-t
print("\n")

#WHILE
print(f"While:", end=" ")
i = 0
while i < T: #Enquanto o contador for menor que o numero apresentado
  print(f"{T-i}", end="") #Mostre o calculo de T-t
  i += 1

"""2. Solicitar um número inteiro positivo N ao usuário. Imprimir os números de N a 1 trocando o sinal dos números. Realizar o exercício usando loops for e while. Exemplo para N igual a 5:"""

N = int(input("Entre com numero inteiro maior que 1 "))
#FOR
print(f"For:", end=" ")
for n in range(N):
  print(f"-{n}", end="")  #print(f'-{n}')

N = int(input("Entre com numero inteiro maior que 1"))
#WHILE
print(f"While:", end=" ")
n = 0
while n < N:
  print(f"{(N-n)*-1}", end="")
  n +=1

# Resolucao Caique

N = int(input("Entre com numero inteiro maior que 1"))
#for
print("For:")
mult = -1
fat = 1
for n in range(N):
  num = fat * (N-n)
  fat *=mult
  print(f"{num}", end=" ")
print("\n")

#while
print("While:")
mult =-1
fat = 1
i = 0
while i < N:
  num = fat * (N-i)
  fat *= mult
  print(f"{num}", end=" ")
  i += 1

"""3. Solicitar um numero inteiro positivo N ao usuario e imprimir i² para i maior do que 0 e menor que i

"""

N = int(input("Entre com numero inteiro maior que 1 "))
#for
print("For:")
for i in range (1, N):
  print(f"{i*i}")

#while
print("while")
i = 1
while i < N:
  print(f"{i*i}")
  i += 1

# 5 -4 3 -2 1

N = 5
mult = -1
fat = 1
for n in range(N):
  print(fat * (N - n), end=" ")
  fat = fat * mult

# Dado N inteiro imprimir i*i par 0<=i<N
N = int(input("Entre com N>0 "))
"""
N = 3
0*0 i=0
1*1 i=1
2*2 i=2 < N
"""
print(f"   i   i*i  i**3")
for i in range(N):
  print(f"{i:4d} {i*i:4d} {i**3:4d}")

# 5. Solicitar uma palavra ao usuario e dizer se a palavra e um palindromo, isto e, pode ser lida igualmente da esquerda para a direita e vice-versa. Exemplos de palavras que sao palindromos: ovo, radar, mirim, arara, reviver. Algumas dicas

#palavra = "dados"
#N = len(palavra) # tamanho de uma palavra em caracteres
#print(N) #saida esperada: 5
# indexando caracteres de uma palavra:
#print(palavra[0]) # saida esperada: d
#print(palavra[1]) # saida esperada: a
#print(palavra[N-1]) # saida esperada: s
#print(palavra[-1]) # saida esperada: s

palavra = str(input('Digite uma palavra para verificar: ')).strip().lower()
invertida  = palavra[::-1]
if palavra == invertida:
  print(f'A palavra {palavra} e um  palindromo')
else:
   print(f'A palavra {palavra} nao e um palindromo')

#6 .Fazer um programa que solicita um numero inteiro positivo N ao usuario e imprime o seguinte padrao na tela. Por exemplo, para

# N = 1

#  -
# | |
#  -

# N = 2

#  --
# |  |
# |  |
#  --

# N = 5

# -----
# |   |
# |   |
# |   |
# |   |
# |   |
# -----


numero = int(input('Digite um numero: '))
print(' ', end='')
print('-'*numero)
for vezes in range(numero):
  print('|', end='')
  print(' '*numero, end='')
  print('|')

print(' ', end='')
print('-'*numero)

# 7. Fazer um programa que socilita um numero inteiro positivo N ao usario e imprime o seguinte padrao na tela. Por exemplo, para N = 5.

# *
# **

# ***

# ****

# *****



n = int(input("Digite um número inteiro positivo: "))

for i in range(1, n + 1):
    print('+' * i)